Program.create( :name => "Master of Computer Science", :acronym => "MCS", :is_thesis => false)
Program.create( :name => "Master of Engineering in Computer Science", :acronym => "MEN", :is_thesis => false)
Program.create( :name => "Master of Science in Computer Science", :acronym => "MSCS", :is_thesis => true)
Program.create( :name => "Master of Science in Computer Engineering", :acronym => "MSCE", :is_thesis => true)
Course.create( :department => "CSCE", :number => 603, :name => "Database Systems and Applications", :credit => 3, :description => "Introduction to the concepts and design methodologies of database systems for non-computer science majors; emphasis on E. F. Codd's relational model with hands-on design application. No credit will be given for both CSCE 310 and CSCE 603. Prerequisites: CSCE 601; graduate classification.", :is_fall => false, :is_spring => true, :is_summer => false)
Course.create( :department => "CSCE", :number => 604, :name => "Programming Languages", :credit => 3, :description => "Study in the design space of programming languages, covering language processing, formalisms to describe semantics of programming languages, important concepts found in current programming languages, and programming paradigms. Prerequisite: Graduate classification.", :is_fall => true, :is_spring => false, :is_summer => false)
Course.create( :department => "CSCE", :number => 605, :name => "Compiler Design", :credit => 3, :description => "Advanced topics in compiler writing; parser generators and compiler-compilers; dynamic storage and scope resolution; data flow analysis and code optimization. Prerequisite: CSCE 434.", :is_fall => false, :is_spring => true, :is_summer => false)
Course.create( :department => "CSCE", :number => 606, :name => "Software Engineering", :credit => 3, :description => "Development of advanced concepts in software engineering; software development environments as a mechanism for enhancing productivity and software quality; the classification, evaluation and selection of methodologies for environments; rapid prototyping and reusability concepts; artificial intelligence techniques applied to software engineering. Prerequisite: CSCE 431 or approval of instructor.", :is_fall => true, :is_spring => true, :is_summer => false)
Course.create( :department => "CSCE", :number => 608, :name => "Database Systems", :credit => 3, :description => "Database modeling techniques; expressiveness in query languages including knowledge representation; manipulation languages data models; physical data organization; relational database design theory; query processing; transaction management and recovery; distributed data management. Prerequisite: CSCE 310 or CSCE 603.", :is_fall => true, :is_spring => false, :is_summer => false)
Course.create( :department => "CSCE", :number => 611, :name => "Operating Systems and Applications", :credit => 3, :description => "Review of computer architecture hardware/software evolution leading to contemporary operating systems; basic operating systems concepts; methods of operating systems design and construction; algorithms for CPU scheduling memory and general resource allocation; process coordination and management; case studies of several operating systems; quality-of-services of operating systems and their impact on applications. No credit will be given for both CSCE 410 and CSCE 611. Prerequisites: CSCE 313; graduate classification.", :is_fall => true, :is_spring => true, :is_summer => false)
Coursesection.create( :department => "CSCE", :number => 603, :section => 600, :instructor => "JIANG A", :term => "Spring", :year => 2013, :gpa => 4, :student => 17, :a => "100.00%", :b => "0.00%", :c => "0.00%", :d => "0.00%", :f => "0.00%", :q => "0.00%", :course_id => 1)
Coursesection.create( :department => "CSCE", :number => 603, :section => 600, :instructor => "JIANG A", :term => "Spring", :year => 2014, :gpa => 4, :student => 29, :a => "100.00%", :b => "0.00%", :c => "0.00%", :d => "0.00%", :f => "0.00%", :q => "0.00%", :course_id => 1)
Coursesection.create( :department => "CSCE", :number => 604, :section => 600, :instructor => "JARVI J", :term => "Fall", :year => 2014, :gpa => "3.542", :student => 24, :a => "54.17%", :b => "45.83%", :c => "0.00%", :d => "0.00%", :f => "0.00%", :q => "4.17%", :course_id => 2)
Coursesection.create( :department => "CSCE", :number => 604, :section => 600, :instructor => "JARVI J", :term => "Fall", :year => 2015, :gpa => "3.714", :student => 7, :a => "85.71%", :b => "0.00%", :c => "14.29%", :d => "0.00%", :f => "0.00%", :q => "0.00%", :course_id => 2)
Coursesection.create( :department => "CSCE", :number => 605, :section => 600, :instructor => "RAUCHWERGER L", :term => "Spring", :year => 2013, :gpa => "3.667", :student => 6, :a => "66.67%", :b => "33.33%", :c => "0.00%", :d => "0.00%", :f => "0.00%", :q => "0.00%", :course_id => 3)
Coursesection.create( :department => "CSCE", :number => 605, :section => 600, :instructor => "RAUCHWERGER L", :term => "Spring", :year => 2015, :gpa => "3.556", :student => 9, :a => "66.67%", :b => "22.22%", :c => "11.11%", :d => "0.00%", :f => "0.00%", :q => "11.11%", :course_id => 3)
Coursesection.create( :department => "CSCE", :number => 606, :section => 600, :instructor => "WALKER D", :term => "Fall", :year => 2013, :gpa => "3.951", :student => 102, :a => "98.04%", :b => "0.98%", :c => "0.00%", :d => "0.00%", :f => "0.98%", :q => "0.00%", :course_id => 4)
Coursesection.create( :department => "CSCE", :number => 606, :section => 600, :instructor => "WALKER D", :term => "Fall", :year => 2014, :gpa => "3.83", :student => 100, :a => "84.00%", :b => "15.00%", :c => "1.00%", :d => "0.00%", :f => "0.00%", :q => "0.00%", :course_id => 4)
Coursesection.create( :department => "CSCE", :number => 606, :section => 600, :instructor => "HUANG S", :term => "Fall", :year => 2015, :gpa => "3.953", :student => 85, :a => "95.29%", :b => "4.71%", :c => "0.00%", :d => "0.00%", :f => "0.00%", :q => "0.00%", :course_id => 4)
Coursesection.create( :department => "CSCE", :number => 606, :section => 600, :instructor => "WALKER D", :term => "Spring", :year => 2015, :gpa => 4, :student => 57, :a => "100.00%", :b => "0.00%", :c => "0.00%", :d => "0.00%", :f => "0.00%", :q => "0.00%", :course_id => 4)
Coursesection.create( :department => "CSCE", :number => 606, :section => 600, :instructor => "WALKER D", :term => "Spring", :year => 2016, :gpa => "3.603", :student => 73, :a => "61.64%", :b => "36.99%", :c => "1.37%", :d => "0.00%", :f => "0.00%", :q => "0.00%", :course_id => 4)
Coursesection.create( :department => "CSCE", :number => 608, :section => 600, :instructor => "JIANG A", :term => "Fall", :year => 2013, :gpa => "3.986", :student => 74, :a => "98.65%", :b => "1.35%", :c => "0.00%", :d => "0.00%", :f => "0.00%", :q => "0.00%", :course_id => 5)
Coursesection.create( :department => "CSCE", :number => 608, :section => 600, :instructor => "JIANG A", :term => "Fall", :year => 2014, :gpa => "3.429", :student => 98, :a => "42.86%", :b => "57.14%", :c => "0.00%", :d => "0.00%", :f => "0.00%", :q => "1.02%", :course_id => 5)
Coursesection.create( :department => "CSCE", :number => 608, :section => 600, :instructor => "CHEN J", :term => "Fall", :year => 2015, :gpa => "3.259", :student => 58, :a => "31.03%", :b => "63.79%", :c => "5.17%", :d => "0.00%", :f => "0.00%", :q => "0.00%", :course_id => 5)
Coursesection.create( :department => "CSCE", :number => 611, :section => 600, :instructor => "LEYK T", :term => "Fall", :year => 2014, :gpa => "3.81", :student => 21, :a => "85.71%", :b => "9.52%", :c => "4.76%", :d => "0.00%", :f => "0.00%", :q => "0.00%", :course_id => 6)
Coursesection.create( :department => "CSCE", :number => 611, :section => 500, :instructor => "BETTATI R", :term => "Spring", :year => 2014, :gpa => "3.556", :student => 18, :a => "55.56%", :b => "44.44%", :c => "0.00%", :d => "0.00%", :f => "0.00%", :q => "11.11%", :course_id => 6)
Coursesection.create( :department => "CSCE", :number => 611, :section => 600, :instructor => "DA S", :term => "Fall", :year => 2015, :gpa => "3.956", :student => 23, :a => "95.65%", :b => "4.35%", :c => "0.00%", :d => "0.00%", :f => "0.00%", :q => "4.35%", :course_id => 6)
Package.create( :number => 1)
Package.create( :number => 2)
Package.create( :number => 3)
Package.create( :number => 4)
Package.create( :number => 5)
Semester.create( :term => "Spring", :year => 2017)
Semester.create( :term => "Fall", :year => 2017)
Semester.create( :term => "Spring", :year => 2018)
Student.create( :firstname => "Johana", :lastname => "Rueda", :email => "xxx@tamu.edu", :password => "xxx", :is_f1 => false, :program_id => 1)
Student.create( :firstname => "Yining", :lastname => "Bao", :email => "yyy@tamu.edu", :password => "yyy", :is_f1 => true, :program_id => 2)
Student.create( :firstname => "Andres", :lastname => "Gonzalez", :email => "xxx@tamu.edu", :password => "xxx", :is_f1 => true, :program_id => 3)
Student.create( :firstname => "Shijin", :lastname => "Tang", :email => "yyy@tamu.edu", :password => "yyy", :is_f1 => true, :program_id => 4)
Student.create( :firstname => "Jingjia", :lastname => "Li", :email => "xxx@tamu.edu", :password => "xxx", :is_f1 => false, :program_id => 1)
ProgramCoursePackageship.create( :program_id => 1, :course_id => 1, :package_id => 1)
ProgramCoursePackageship.create( :program_id => 1, :course_id => 2, :package_id => 1)
ProgramCoursePackageship.create( :program_id => 1, :course_id => 3, :package_id => 2)
ProgramCoursePackageship.create( :program_id => 1, :course_id => 4, :package_id => 2)
ProgramCoursePackageship.create( :program_id => 1, :course_id => 5, :package_id => 2)
ProgramCoursePackageship.create( :program_id => 2, :course_id => 1, :package_id => 1)
ProgramCoursePackageship.create( :program_id => 2, :course_id => 6, :package_id => 1)
ProgramCoursePackageship.create( :program_id => 2, :course_id => 2, :package_id => 2)
ProgramCoursePackageship.create( :program_id => 3, :course_id => 1, :package_id => 1)
ProgramCoursePackageship.create( :program_id => 4, :course_id => 3, :package_id => 1)
StudentCourseSemestership.create( :student_id => 1, :course_id => 6, :semester_id => 1)
StudentCourseSemestership.create( :student_id => 1, :course_id => 4, :semester_id => 1)
StudentCourseSemestership.create( :student_id => 1, :course_id => 1, :semester_id => 2)
StudentCourseSemestership.create( :student_id => 2, :course_id => 6, :semester_id => 1)
StudentCourseSemestership.create( :student_id => 3, :course_id => 4, :semester_id => 1)
StudentCourseSemestership.create( :student_id => 4, :course_id => 1, :semester_id => 2)
StudentCourseSemestership.create( :student_id => 5, :course_id => 1, :semester_id => 2)
